### ISSUE TITLE
variable edition does not work on server

### ISSUE THREAD

**Issue by simonaubertbd** [kabir-rab/Variable-Editor#1]
Hello,

(first of all, thanks for your work, I really appreciate your effort)
I try to edit a frontend variable on a Feb 2019 Server.

I can develop the variable with +. The edit button is green. I can write something. However it's not saved at all.

Best regards,

Simon

**Comment by kabir-rab** [comment]
The functionality is not there yet. Users can only view but not -edit/save then. This was planned for future release - which never really happened due to lack time. I will look at picking this up in near future.
