### ISSUE TITLE
Download Load Script does not work with published apps

### ISSUE THREAD

**Issue by simonaubertbd** [kabir-rab/Variable-Editor#2]
Hello,

Just like stated in the title : I cannot download script for published apps (but it works great for apps in my work).

Best regards,

Simon

**Comment by kabir-rab** [comment]
Thank you for using it and I will take a look - It was a concept and I haven't really picked this up since its inception - I will look at it when I have some spare time next.

**Comment by kabir-rab** [comment]
I have just tested this on QSE November 2018 and November 2019 for both published and non published, I was able to download the script. I believe this is down to the permission level - I am root admin on those both test environments. This will be impacted by permission you have for the published app/stream in questions. I will do a followup test with a test account later to check the.

**Comment by simonaubertbd** [comment]
@kabir-rab I'm also root admin. I think you have to be content Admin to make it work. I just add the role to my user and now I have access to the script. Sorry for the issue, I didn't check.

(but can you please mention in documentation this requirement?)
